local HairColors = {}

HairColors.WhiteHairColors = {
	Color3.fromRGB(86, 66, 54),
	Color3.fromRGB(99, 95, 98),
	Color3.fromRGB(17, 17, 17),
	Color3.fromRGB(159, 161, 172),
	Color3.fromRGB(188, 155, 93),
	Color3.fromRGB(248, 217, 109),
	Color3.fromRGB(70, 42, 0),
	Color3.fromRGB(60, 50, 40),
	Color3.fromRGB(60, 50, 40),
	Color3.fromRGB(27, 42, 53),
	Color3.fromRGB(170, 85, 0)
}
	
HairColors.BlackHairColors = {
	Color3.fromRGB(17, 17, 17),
	Color3.fromRGB(27, 42, 53),
	Color3.fromRGB(40, 40, 40),
	Color3.fromRGB(159, 161, 172)
}


return HairColors
