local SkinColors = {}

SkinColors.WhiteSkinColors = {
	Color3.fromRGB(255, 204, 153),
	Color3.fromRGB(240, 180, 150),
	Color3.fromRGB(167, 125, 104),
	Color3.fromRGB(170, 136, 102),
	Color3.fromRGB(118, 94, 71),
	Color3.fromRGB(189, 163, 133)
}

SkinColors.BlackSkinColors = {
	Color3.fromRGB(90, 76, 66),
	Color3.fromRGB(65, 59, 48),
	Color3.fromRGB(160, 110, 70),
	Color3.fromRGB(136, 110, 84),
	Color3.fromRGB(118, 94, 71)
}

SkinColors.AlienSkinColors = {
	Color3.fromRGB(135, 255, 108),
	Color3.fromRGB(219, 255, 152),
	Color3.fromRGB(135, 255, 219),
	Color3.fromRGB(239, 192, 255),
	Color3.fromRGB(194, 218, 184),
	Color3.fromRGB(184, 184, 184)
}


return SkinColors
